# Generated by Django 4.2.4 on 2023-08-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
    ]
